version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    depends_on:
      - db
    networks:
      - app_net
  db:
    image: "postgres:14.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes: /var/lib/postgres:/var/lib/postgres
    networks:
      - app_net
networks:
  app_net:
    driver: bridge